import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

const config = [
  // next-env.d.ts is generated by Next.js and is not ours to lint.
  { ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'] },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // These render to PDF via @react-pdf/renderer, not to the DOM. Its <Image>
    // takes no alt text and Next's <Image> rules do not apply.
    files: ['src/server/documents/pdf/**/*.tsx'],
    rules: { 'jsx-a11y/alt-text': 'off', '@next/next/no-img-element': 'off' },
  },
]

export default config
